### ISSUE TITLE
Remove vertical spaces between images 

### ISSUE THREAD

**Issue by PARobert** [tokee/juxta#38]
The option MARGIN controls spaces left between two images horizontally. Is it any option to control spaces between two images vertically ?

**Comment by tokee** [comment]
`MARGIN`controls both horizontal and vertical. It is also cumulative, so a margin of 10 means 20 pixels between images. In retrospect, this might not have been the best decision.

Anyway, it was easy to add separate margins for horizontal and vertical, so if you want a bit of margin on the x-axis and want your images to touch each other vertically, you can now do `MARGIN_H=10 MARGIN_V=0`. Or at least: You should be able to. There seems to be a bug that makes it impossible to get a 0-size margin. I'll look into that in issue #39.

*Correction 2017-03-13:* The arguments are `MARGIN_W` and `MARGIN_H`. And they work just fine.

**Comment by tokee** [comment]
I was mistaken about 0 margin not working. See issue #39 for details.
