### ISSUE TITLE
RAW_MODE=automax fails with spaces in file names

### ISSUE THREAD

**Issue by tokee** [tokee/juxta#67]
@thomasegense discovered that the option `RAW_MODE=automax` makes juxta skip images with spaces (or at least say it does). Same with `ALLOW_UPSCALE=true`.

**Comment by thomasegense** [comment]
To bypass the error and not using RAW_MODE, define the x-gap and y-gap instead  with
RAW_W=3 RAW_H=4

**Comment by tokee** [comment]
I traced this back to an installation problem in Python: If a package (`rasterfairy` being the primary culprit) was missing, similarity sort produced a halfway-functioning image list. The commit d1a635cb1877012a37c4a3f529284b506f93ed43 adds a check for similarity sorting actually returning something.

Related, 9e4f5c5295ddf62c8c2ff620a69b7626e6b4ef33 changes the Python package installation process to install binary packed only - it is likely that an aborted installation, due to very long compile time for supporting libraries, was the cause of the troubles for @thomasegense 

I advise deleting the folder `tensorflow/virtualenv` after upgrading juxta, to make sure the requirements are up to date. And maybe **re-run any jobs relying on image similarity sort** (remember to delete the destination folder to guard against residue from previous runs), to make sure they are actually similarity sorted and not just original order?

**Comment by tokee** [comment]
I'll close this issue for now as the issue has been reproduced (okay, probably reproduced) and the issue fixed.
