### ISSUE TITLE
Use this tool to create PhotoMosaics?

### ISSUE THREAD

**Issue by Snazzyham** [tokee/juxta#77]
Sorry if this doesn't belong here, but I'm trying to implement a feature similar to https://mosaically.com using deepzoom where each individual photo in the mosiac can be hovered over to reveal its title name, similar to what the juxta/demo_gallery,sh script does. 

Does anyone have any advice on how I would go about achieving something like this? 

Thanks

**Comment by tokee** [comment]
Sorry, I don't understand the context of your question. Since both Mosaically and Juxta (using the gallery-script) seems to do what you want, where do you need the functionality? Are you building a different OpenSeadragon-based thing?

**Comment by Snazzyham** [comment]
@tokee I could get the gallery script to show the whole gallery with like individual images, but I was looking for something more like mosiacally.com, where you can set a target image which will be the larger image, and the smaller individual images will be color blended to match. I didn't want to use mosiacally cause I wanted control over the openseadragon instance. It's all good though, I solved by using [AndreaMosaic](http://www.andreaplanet.com/andreamosaic/) and converting the exported image to a `.dzi` with vips. 

Thank you for this tool though, reading through the code helped me figure out how to build what I needed to, really appreciate it!
